"""
Cognex XML Tool
================

Author: Hemy Gulati
Version: 1.1.0
GitHub: https://github.com/HemyGulati/CognexXMLTool

A Tkinter desktop GUI for combining Cognex XML image-path exports with Cognex
CSV runtime result exports.

XML + CSV workflow
------------------
- XML provides image names, image paths, and image order.
- CSV provides actual runtime result values.
- The tool merges both inputs, lets the user select tests/result conditions,
  then exports CSV/TXT outputs and can copy matched images to a folder.

The source is intentionally kept as a single Python file so it is easy to review,
edit, and package into a standalone Windows EXE using PyInstaller.
"""

from __future__ import annotations

import csv
import ctypes
import json
import os
import re
import shutil
import sys
import traceback
import webbrowser
import xml.etree.ElementTree as ET
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Set, Tuple

import tkinter as tk
from tkinter import filedialog, messagebox, ttk
from tkinter.scrolledtext import ScrolledText


# -----------------------------------------------------------------------------
# Application metadata
# -----------------------------------------------------------------------------

APP_NAME = "Cognex XML Tool"
APP_VERSION = "1.1.0"
APP_AUTHOR = "Hemy Gulati"
APP_GITHUB = "https://github.com/HemyGulati/CognexXMLTool"
APP_LICENSE = "MIT License"


# -----------------------------------------------------------------------------
# Configuration constants
# -----------------------------------------------------------------------------

IMAGE_EXTENSIONS = {".bmp", ".jpg", ".jpeg", ".png", ".tif", ".tiff"}
PATH_TAGS = ["RefPath", "Path", "ImagePath", "FilePath"]

ANY_TARGET = "(Any / output only)"
MISSING_TARGET = "(Missing / blank)"

MATCH_MODE_ALL = "ALL selected result conditions"
MATCH_MODE_ANY = "ANY selected result condition"

DEFAULT_ALL_RESULTS_CSV = "selected_test_results.csv"
DEFAULT_MATCHED_RESULTS_CSV = "matched_results.csv"
DEFAULT_MATCHED_PATHS_TXT = "matched_image_paths.txt"
DEFAULT_IMAGE_FOLDER = "images"
CONFIG_FILENAME = "cognex_xml_tool_config.json"
WINDOWS_INVALID_PATH_CHARS = r'<>:"/\\|?*'

# CSV columns that are normally metadata rather than inspection result columns.
CSV_METADATA_COLUMNS = {
    "record",
    "image",
    "imagename",
    "image name",
    "image_name",
    "filename",
    "file name",
    "path",
    "imagepath",
    "image path",
    "filepath",
    "file path",
    "station",
    "program",
    "counter",
    "timestamp",
    "time",
    "date",
    "result",
}

IMAGE_KEY_CANDIDATES = [
    "ImageName",
    "Image Name",
    "image name",
    "image_name",
    "Filename",
    "FileName",
    "File Name",
    "ImagePath",
    "Image Path",
    "image path",
    "Path",
    "FilePath",
    "File Path",
]

RECORD_KEY_CANDIDATES = ["Record", "record", "Index", "ImageIndex", "Image Index", "ID"]


# -----------------------------------------------------------------------------
# Data models
# -----------------------------------------------------------------------------

@dataclass
class XmlImage:
    """Image metadata read from the Cognex XML file."""

    image_name: str
    image_path: str = ""
    source_xml: str = ""


@dataclass
class CsvTestColumn:
    """A CSV result column that can be selected as an inspection/test."""

    display_name: str
    csv_column: str
    detected_values: Set[str] = field(default_factory=set)
    rows_with_data: int = 0


@dataclass
class ImageRecord:
    """Merged image record after XML image metadata is combined with CSV results."""

    image_name: str
    image_path: str = ""
    results: Dict[str, str] = field(default_factory=dict)
    csv_rows: int = 0


@dataclass
class MergedData:
    """All merged records and detected test metadata used by the GUI."""

    records: Dict[str, ImageRecord] = field(default_factory=dict)
    image_order: List[str] = field(default_factory=list)
    tests: Dict[str, CsvTestColumn] = field(default_factory=dict)
    xml_files: List[Path] = field(default_factory=list)
    csv_file: Optional[Path] = None
    csv_key_mode: str = ""
    csv_rows_loaded: int = 0
    xml_images_loaded: int = 0
    csv_groups_matched: int = 0
    csv_groups_unmatched: int = 0


@dataclass
class Condition:
    """Selected test and result filter condition."""

    test_name: str
    target_result: str = ANY_TARGET


@dataclass
class OutputSummary:
    """Summary of files generated by the processing step."""

    output_folder: Optional[Path] = None
    total_images: int = 0
    tests_selected: int = 0
    filter_conditions: int = 0
    matched_images: int = 0
    all_results_csv: Optional[Path] = None
    matched_results_csv: Optional[Path] = None
    matched_paths_txt: Optional[Path] = None


@dataclass
class CopySummary:
    """Summary of image-copy operation."""

    total_paths: int = 0
    copied: int = 0
    missing: int = 0
    skipped_blank: int = 0
    errors: int = 0
    destination_folder: Optional[Path] = None


# -----------------------------------------------------------------------------
# General helpers
# -----------------------------------------------------------------------------

def set_windows_app_user_model_id() -> None:
    """Set a Windows AppUserModelID so the taskbar uses the app icon.

    This is mainly useful for source/portable runs. The packaged EXE also gets
    its icon from PyInstaller via the --icon option in build_exe.bat.
    """

    if os.name != "nt":
        return

    try:
        ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(
            f"HemyGulati.{APP_NAME.replace(' ', '')}.{APP_VERSION}"
        )
    except Exception:
        # The app should still run if Windows does not accept the AppUserModelID.
        pass

def app_base_dir() -> Path:
    """Return the folder beside the script or beside the packaged EXE."""

    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve().parent
    return Path(__file__).resolve().parent




def resource_path(relative_path: str) -> Path:
    """Return a resource path that works in source and PyInstaller builds."""

    if hasattr(sys, "_MEIPASS"):
        return Path(getattr(sys, "_MEIPASS")) / relative_path
    return app_base_dir() / relative_path


def user_config_dir() -> Path:
    """Return the stable per-user config folder.

    The config is intentionally not saved beside the EXE. When the app is
    installed under Program Files, that folder is normally read-only for
    standard users. Using AppData keeps the app installer-friendly and avoids
    config files appearing in random launch/download folders.
    """

    if os.name == "nt":
        base = os.environ.get("APPDATA")
        if base:
            return Path(base) / "CognexXMLTool"
        return Path.home() / "AppData" / "Roaming" / "CognexXMLTool"

    # Fallback for non-Windows development/testing.
    return Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "CognexXMLTool"


def config_path() -> Path:
    """Return the default config path used for auto-load/auto-save."""

    return user_config_dir() / CONFIG_FILENAME


def legacy_config_path() -> Path:
    """Return the old config location used by earlier portable builds."""

    return app_base_dir() / CONFIG_FILENAME


def ensure_config_folder() -> None:
    """Create the config folder if it does not already exist."""

    user_config_dir().mkdir(parents=True, exist_ok=True)


def local_name(tag: str) -> str:
    """Return XML tag name without namespace."""

    return tag.split("}", 1)[-1]


def direct_child_text(parent: ET.Element, possible_names: Iterable[str]) -> str:
    """Return text from the first matching direct child tag name."""

    wanted = {name.lower() for name in possible_names}
    for child in list(parent):
        if local_name(child.tag).lower() in wanted:
            return (child.text or "").strip()
    return ""


def is_image_name(value: str) -> bool:
    """Return True if the supplied text looks like an image filename/path."""

    return Path(value or "").suffix.lower() in IMAGE_EXTENSIONS


def image_basename(value: str) -> str:
    """Return only the image filename from a filename or full path."""

    return Path((value or "").strip().strip('"')).name


def natural_key(value: str) -> List[object]:
    """Natural sorting key, e.g. image_2 before image_10."""

    parts = re.split(r"(\d+)", value)
    return [int(part) if part.isdigit() else part.lower() for part in parts]


def normalise_result(value: object) -> str:
    """Convert common Cognex/CSV values into consistent result labels."""

    text = str(value or "").strip()
    lower = text.lower()
    common = {
        "1": "Pass",
        "1.0": "Pass",
        "true": "Pass",
        "yes": "Pass",
        "y": "Pass",
        "ok": "Pass",
        "pass": "Pass",
        "passed": "Pass",
        "0": "Fail",
        "0.0": "Fail",
        "false": "Fail",
        "no": "Fail",
        "n": "Fail",
        "ng": "Fail",
        "fail": "Fail",
        "failed": "Fail",
    }
    return common.get(lower, text)


def is_pass_value(value: object) -> bool:
    """Return True when a raw or normalised value means pass."""

    return normalise_result(value).lower() == "pass"


def is_fail_value(value: object) -> bool:
    """Return True when a raw or normalised value means fail."""

    return normalise_result(value).lower() == "fail"


def unique_destination_path(destination_folder: Path, filename: str) -> Path:
    """Return a destination path that will not overwrite an existing file."""

    destination = destination_folder / filename
    if not destination.exists():
        return destination

    stem = destination.stem
    suffix = destination.suffix
    counter = 1
    while True:
        candidate = destination_folder / f"{stem}_copy{counter}{suffix}"
        if not candidate.exists():
            return candidate
        counter += 1




def sanitize_path_part(value: str, max_length: int = 120) -> str:
    """Return text safe to use as a Windows folder name."""

    text = str(value or "").strip()
    for char in WINDOWS_INVALID_PATH_CHARS:
        text = text.replace(char, "_")
    text = re.sub(r"\s+", "_", text)
    text = re.sub(r"_+", "_", text).strip(" _." )
    if not text:
        text = "selected_results"
    return text[:max_length].rstrip(" _." ) or "selected_results"


def condition_folder_name(conditions: Sequence[Condition], match_mode: str) -> str:
    """Build a readable output folder name from selected tests/results."""

    parts: List[str] = []
    for condition in conditions:
        test = sanitize_path_part(condition.test_name, max_length=40)
        target = condition.target_result or ANY_TARGET
        if target == ANY_TARGET:
            result = "Any"
        elif target == MISSING_TARGET:
            result = "Missing"
        else:
            result = sanitize_path_part(target, max_length=30)
        parts.append(f"{test}_{result}")

    joiner = "_OR_" if match_mode.lower().startswith("any") else "_AND_"
    return sanitize_path_part(joiner.join(parts), max_length=180)


def default_output_base_folder(csv_file: Optional[Path]) -> Path:
    """Return the default base folder for outputs: the CSV file folder if known."""

    if csv_file:
        return csv_file.resolve().parent
    return Path.cwd()

def output_image_path(image_name: str, xml_image_path: str, image_root_override: Optional[str]) -> str:
    """Return the image path to write to CSV/TXT outputs."""

    if image_root_override:
        return str(Path(image_root_override) / image_name)
    if xml_image_path:
        return xml_image_path
    return image_name


# -----------------------------------------------------------------------------
# XML parsing: image names, image paths, and order only
# -----------------------------------------------------------------------------

def parse_xml_images(xml_path: Path) -> List[XmlImage]:
    """Read image names and paths from a Cognex XML summary file.

    Version 2 intentionally does not use the XML result values because the XML
    exports seen in this workflow contain expected results rather than actual
    runtime results. Actual results are read from the Cognex CSV export instead.
    """

    tree = ET.parse(xml_path)
    root = tree.getroot()
    images: List[XmlImage] = []

    for folder in root.iter():
        if local_name(folder.tag) != "ValidationFolder":
            continue

        image_name = (folder.attrib.get("Name") or "").strip()
        if not is_image_name(image_name):
            continue

        image_path = ""
        for child in list(folder):
            if local_name(child.tag) == "Validate":
                ref_path = direct_child_text(child, PATH_TAGS)
                if ref_path:
                    image_path = ref_path
                    break

        images.append(XmlImage(image_name=image_name, image_path=image_path, source_xml=str(xml_path)))

    return images


def merge_xml_images(xml_files: Sequence[Path]) -> Tuple[Dict[str, XmlImage], List[str]]:
    """Merge images from one or more XML files while preserving first-seen order."""

    images_by_name: Dict[str, XmlImage] = {}
    image_order: List[str] = []

    for xml_file in xml_files:
        for image in parse_xml_images(xml_file):
            if image.image_name not in images_by_name:
                images_by_name[image.image_name] = image
                image_order.append(image.image_name)
            elif not images_by_name[image.image_name].image_path and image.image_path:
                images_by_name[image.image_name].image_path = image.image_path

    return images_by_name, image_order


# -----------------------------------------------------------------------------
# CSV parsing and result aggregation
# -----------------------------------------------------------------------------

def read_csv_rows(csv_path: Path) -> Tuple[List[Dict[str, str]], List[str]]:
    """Read CSV rows using utf-8-sig so Excel BOM files are handled.

    Cognex/Excel CSV exports can sometimes include a final blank line that
    DictReader interprets as a row of empty values. Those blank rows are ignored
    so they do not appear as unmatched records in the scan summary.
    """

    with csv_path.open("r", newline="", encoding="utf-8-sig") as file:
        reader = csv.DictReader(file)
        fieldnames = list(reader.fieldnames or [])
        rows: List[Dict[str, str]] = []
        for row in reader:
            cleaned = {key: (value or "").strip() for key, value in row.items()}
            if any(value != "" for value in cleaned.values()):
                rows.append(cleaned)
    return rows, fieldnames


def find_first_column(fieldnames: Sequence[str], candidates: Sequence[str]) -> Optional[str]:
    """Find a CSV column by case-insensitive candidate names."""

    lower_map = {name.lower(): name for name in fieldnames}
    for candidate in candidates:
        match = lower_map.get(candidate.lower())
        if match:
            return match
    return None


def looks_boolean_result_column(rows: Sequence[Dict[str, str]], column: str) -> bool:
    """Return True if a column looks like pass/fail, true/false, or 1/0 data."""

    values = {str(row.get(column, "")).strip().lower() for row in rows if str(row.get(column, "")).strip() != ""}
    if not values:
        return False
    allowed = {"0", "1", "0.0", "1.0", "true", "false", "pass", "fail", "passed", "failed", "ok", "ng", "yes", "no", "y", "n"}
    return values.issubset(allowed)


def display_name_for_csv_column(column: str) -> str:
    """Convert CSV result column names to friendlier test names."""

    if column.lower().endswith("pass") and len(column) > 4:
        return column[:-4]
    return column


def detect_csv_result_columns(rows: Sequence[Dict[str, str]], fieldnames: Sequence[str]) -> Dict[str, CsvTestColumn]:
    """Detect selectable inspection result columns from the Cognex CSV.

    Version 2 primarily expects actual result columns that end in Pass, such as
    InspectionAPass, InspectionBPass, and OverallPass. These are displayed
    without the Pass suffix where possible.

    If no *Pass columns exist, the function falls back to other boolean-looking
    non-metadata columns so the app can still be useful for other Cognex exports.
    Percentage/score columns such as InspectionAPct are intentionally excluded
    from the result-condition list.
    """

    def is_excluded(column_name: str) -> bool:
        name = column_name.strip().lower()
        return (
            name in CSV_METADATA_COLUMNS
            or name.endswith("pct")
            or name.endswith("percent")
            or name.endswith("percentage")
            or name.endswith("score")
            or name.endswith("confidence")
        )

    pass_columns = [column for column in fieldnames if column.strip().lower().endswith("pass") and not is_excluded(column)]
    candidate_columns = pass_columns

    if not candidate_columns:
        candidate_columns = [
            column
            for column in fieldnames
            if not is_excluded(column) and looks_boolean_result_column(rows, column)
        ]

    tests: Dict[str, CsvTestColumn] = {}
    for column in candidate_columns:
        display_name = display_name_for_csv_column(column)
        values: Set[str] = set()
        rows_with_data = 0
        for row in rows:
            raw = row.get(column, "")
            if raw != "":
                rows_with_data += 1
                values.add(normalise_result(raw))

        # If a display name already exists, keep the original column name as a
        # suffix to avoid collisions.
        original_display_name = display_name
        suffix = 2
        while display_name in tests:
            display_name = f"{original_display_name} ({suffix})"
            suffix += 1

        tests[display_name] = CsvTestColumn(
            display_name=display_name,
            csv_column=column,
            detected_values=values,
            rows_with_data=rows_with_data,
        )

    return tests


def group_csv_rows(
    rows: Sequence[Dict[str, str]],
    fieldnames: Sequence[str],
    image_order: Sequence[str],
) -> Tuple[Dict[str, List[Dict[str, str]]], str, int]:
    """Group CSV rows by image name.

    Preferred matching methods:
    1. Use an explicit image/file/path column if present.
    2. Use a Record/Index column as a 1-based pointer into the XML image order.
    3. Fallback to CSV row order as a 1-based pointer into XML image order.
    """

    groups: Dict[str, List[Dict[str, str]]] = defaultdict(list)
    unmatched = 0

    image_key_column = find_first_column(fieldnames, IMAGE_KEY_CANDIDATES)
    if image_key_column:
        for row in rows:
            image_name = image_basename(row.get(image_key_column, ""))
            if image_name:
                groups[image_name].append(row)
            else:
                unmatched += 1
        return groups, f"image column: {image_key_column}", unmatched

    record_column = find_first_column(fieldnames, RECORD_KEY_CANDIDATES)
    if record_column:
        for row in rows:
            raw_record = row.get(record_column, "").strip()
            try:
                record_index = int(float(raw_record))
            except ValueError:
                unmatched += 1
                continue

            xml_index = record_index - 1
            if 0 <= xml_index < len(image_order):
                groups[image_order[xml_index]].append(row)
            else:
                unmatched += 1
        return groups, f"record column: {record_column} mapped to XML order", unmatched

    for row_index, row in enumerate(rows):
        if row_index < len(image_order):
            groups[image_order[row_index]].append(row)
        else:
            unmatched += 1
    return groups, "CSV row order mapped to XML order", unmatched


def aggregate_result_for_column(rows: Sequence[Dict[str, str]], column: str) -> str:
    """Aggregate one CSV result column across one or more rows for the same image.

    Cognex CSV exports may contain multiple rows per image because the job logs
    station/result-specific strings. For Pass columns, the safest aggregation for
    this workflow is:
    - Pass if any row for that image has a pass value.
    - Fail if no pass values exist but at least one fail value exists.
    - Otherwise, return the first non-blank normalised value.
    """

    raw_values = [row.get(column, "") for row in rows if row.get(column, "") != ""]
    if not raw_values:
        return ""

    if any(is_pass_value(value) for value in raw_values):
        return "Pass"
    if any(is_fail_value(value) for value in raw_values):
        return "Fail"

    return normalise_result(raw_values[0])


def merge_xml_and_csv(xml_files: Sequence[Path], csv_file: Path) -> MergedData:
    """Merge XML image metadata with actual CSV result data."""

    images_by_name, image_order = merge_xml_images(xml_files)
    rows, fieldnames = read_csv_rows(csv_file)
    tests = detect_csv_result_columns(rows, fieldnames)
    groups, key_mode, unmatched = group_csv_rows(rows, fieldnames, image_order)

    merged = MergedData(
        xml_files=list(xml_files),
        csv_file=csv_file,
        image_order=list(image_order),
        tests=tests,
        csv_key_mode=key_mode,
        csv_rows_loaded=len(rows),
        xml_images_loaded=len(image_order),
        csv_groups_unmatched=unmatched,
    )

    for image_name in image_order:
        image = images_by_name[image_name]
        csv_group = groups.get(image_name, [])
        record = ImageRecord(image_name=image.image_name, image_path=image.image_path, csv_rows=len(csv_group))

        if csv_group:
            merged.csv_groups_matched += 1
            for test_name, test_column in tests.items():
                record.results[test_name] = aggregate_result_for_column(csv_group, test_column.csv_column)

        merged.records[image_name] = record

    # If the CSV contains explicit image names that were not in the XML, include
    # them so the user can still see that unmatched CSV data existed. These rows
    # will not have XML image paths unless an image-root override is used.
    for image_name, csv_group in groups.items():
        if image_name in merged.records:
            continue
        record = ImageRecord(image_name=image_name, image_path="", csv_rows=len(csv_group))
        for test_name, test_column in tests.items():
            record.results[test_name] = aggregate_result_for_column(csv_group, test_column.csv_column)
        merged.records[image_name] = record
        merged.image_order.append(image_name)
        merged.csv_groups_unmatched += 1

    return merged


# -----------------------------------------------------------------------------
# Filtering and output generation
# -----------------------------------------------------------------------------

def condition_is_filter(condition: Condition) -> bool:
    """Return True when the selected condition should filter matched rows."""

    return condition.target_result not in ("", ANY_TARGET)


def record_matches(record: ImageRecord, conditions: Sequence[Condition], match_mode: str) -> bool:
    """Return True if a record satisfies the selected conditions."""

    filters = [condition for condition in conditions if condition_is_filter(condition)]
    if not filters:
        return True

    checks: List[bool] = []
    for condition in filters:
        actual = (record.results.get(condition.test_name, "") or "").strip()
        target = (condition.target_result or "").strip()
        if target == MISSING_TARGET:
            checks.append(actual == "")
        else:
            checks.append(actual.lower() == target.lower())

    if match_mode.lower().startswith("any"):
        return any(checks)
    return all(checks)


def selected_test_order(conditions: Sequence[Condition]) -> List[str]:
    """Return selected tests in output order while removing duplicates."""

    ordered: List[str] = []
    seen: Set[str] = set()
    for condition in conditions:
        if condition.test_name not in seen:
            ordered.append(condition.test_name)
            seen.add(condition.test_name)
    return ordered


def ordered_records(merged: MergedData) -> List[ImageRecord]:
    """Return records in XML order, then any extra records in natural order."""

    ordered = [merged.records[name] for name in merged.image_order if name in merged.records]
    remaining = sorted(set(merged.records) - set(merged.image_order), key=natural_key)
    ordered.extend(merged.records[name] for name in remaining)
    return ordered


def write_results_csv(records: Sequence[ImageRecord], selected_tests: Sequence[str], csv_path: Path, image_root_override: Optional[str]) -> None:
    """Write image result rows to CSV."""

    csv_path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = ["image name", "image path", "csv rows"] + [f"{test} result" for test in selected_tests]

    with csv_path.open("w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        for record in records:
            row = {
                "image name": record.image_name,
                "image path": output_image_path(record.image_name, record.image_path, image_root_override),
                "csv rows": record.csv_rows,
            }
            for test in selected_tests:
                row[f"{test} result"] = record.results.get(test, "")
            writer.writerow(row)


def write_paths_txt(records: Sequence[ImageRecord], txt_path: Path, image_root_override: Optional[str]) -> None:
    """Write one image path per matched image."""

    txt_path.parent.mkdir(parents=True, exist_ok=True)
    with txt_path.open("w", encoding="utf-8") as file:
        for record in records:
            file.write(output_image_path(record.image_name, record.image_path, image_root_override) + "\n")


def process_outputs(
    merged: MergedData,
    conditions: Sequence[Condition],
    output_folder: Path,
    image_root_override: Optional[str],
    match_mode: str,
    all_csv_name: str = DEFAULT_ALL_RESULTS_CSV,
    matched_csv_name: str = DEFAULT_MATCHED_RESULTS_CSV,
    matched_txt_name: str = DEFAULT_MATCHED_PATHS_TXT,
) -> OutputSummary:
    """Create CSV/TXT outputs from merged XML + CSV data."""

    selected_tests = selected_test_order(conditions)
    if not selected_tests:
        raise ValueError("No tests selected. Add at least one test condition first.")

    all_records = ordered_records(merged)
    matched_records = [record for record in all_records if record_matches(record, conditions, match_mode)]

    all_csv = output_folder / all_csv_name
    matched_csv = output_folder / matched_csv_name
    matched_txt = output_folder / matched_txt_name

    write_results_csv(all_records, selected_tests, all_csv, image_root_override)
    write_results_csv(matched_records, selected_tests, matched_csv, image_root_override)
    write_paths_txt(matched_records, matched_txt, image_root_override)

    return OutputSummary(
        output_folder=output_folder,
        total_images=len(all_records),
        tests_selected=len(selected_tests),
        filter_conditions=sum(1 for condition in conditions if condition_is_filter(condition)),
        matched_images=len(matched_records),
        all_results_csv=all_csv,
        matched_results_csv=matched_csv,
        matched_paths_txt=matched_txt,
    )


def transfer_images_from_txt(paths_txt: Path, destination_folder: Path, move: bool = False) -> CopySummary:
    """Copy or move images listed in the matched image TXT file.

    The matched TXT file is generated by the Run step. Each non-blank line is
    treated as a full image path. Existing destination filenames are protected by
    appending _copy1, _copy2, etc.
    """

    if not paths_txt.exists():
        raise FileNotFoundError(f"Could not find matched image path TXT file: {paths_txt}")

    destination_folder.mkdir(parents=True, exist_ok=True)
    summary = CopySummary(destination_folder=destination_folder)

    with paths_txt.open("r", encoding="utf-8") as file:
        for raw_line in file:
            source_text = raw_line.strip().strip('"')
            if not source_text:
                summary.skipped_blank += 1
                continue

            summary.total_paths += 1
            source_path = Path(source_text)
            if not source_path.exists():
                summary.missing += 1
                continue

            try:
                destination_path = unique_destination_path(destination_folder, source_path.name)
                if move:
                    shutil.move(str(source_path), str(destination_path))
                else:
                    shutil.copy2(source_path, destination_path)
                summary.copied += 1
            except Exception:
                summary.errors += 1

    return summary


def copy_images_from_txt(paths_txt: Path, destination_folder: Path) -> CopySummary:
    """Copy images listed in the matched image TXT file."""

    return transfer_images_from_txt(paths_txt, destination_folder, move=False)


def move_images_from_txt(paths_txt: Path, destination_folder: Path) -> CopySummary:
    """Move images listed in the matched image TXT file."""

    return transfer_images_from_txt(paths_txt, destination_folder, move=True)


def count_matching_records(merged: MergedData, conditions: Sequence[Condition], match_mode: str) -> int:
    """Return how many merged image records currently match the selected filters."""

    return sum(1 for record in ordered_records(merged) if record_matches(record, conditions, match_mode))


# -----------------------------------------------------------------------------
# Small tooltip helper
# -----------------------------------------------------------------------------

class ToolTip:
    """Simple hover tooltip for Tkinter widgets."""

    def __init__(self, widget: tk.Widget, text: str) -> None:
        self.widget = widget
        self.text = text
        self.tip_window: Optional[tk.Toplevel] = None
        widget.bind("<Enter>", self.show)
        widget.bind("<Leave>", self.hide)

    def show(self, _event: Optional[tk.Event] = None) -> None:
        if self.tip_window or not self.text:
            return
        x = self.widget.winfo_rootx() + 20
        y = self.widget.winfo_rooty() + self.widget.winfo_height() + 8
        self.tip_window = tk.Toplevel(self.widget)
        self.tip_window.wm_overrideredirect(True)
        self.tip_window.wm_geometry(f"+{x}+{y}")
        label = ttk.Label(self.tip_window, text=self.text, padding=8, relief="solid", borderwidth=1, wraplength=360)
        label.pack()

    def hide(self, _event: Optional[tk.Event] = None) -> None:
        if self.tip_window:
            self.tip_window.destroy()
            self.tip_window = None


# -----------------------------------------------------------------------------
# GUI application
# -----------------------------------------------------------------------------

class CognexXmlToolGui(tk.Tk):
    """Main Tkinter GUI for Cognex XML + CSV result processing."""

    def __init__(self) -> None:
        super().__init__()
        self.title(f"{APP_NAME} v{APP_VERSION}")
        self._set_window_icon()
        self.geometry("1100x740")
        self.minsize(900, 600)

        self.xml_files: List[Path] = []
        self.csv_file: Optional[Path] = None
        self.merged: Optional[MergedData] = None
        self.conditions: List[Condition] = []
        self.last_summary: Optional[OutputSummary] = None

        self.output_folder = tk.StringVar(value="")
        self.image_root = tk.StringVar(value="")
        self.copy_folder = tk.StringVar(value="")
        self.target_result = tk.StringVar(value="Fail")
        self.match_mode = tk.StringVar(value=MATCH_MODE_ALL)
        self.all_csv_name = tk.StringVar(value=DEFAULT_ALL_RESULTS_CSV)
        self.matched_csv_name = tk.StringVar(value=DEFAULT_MATCHED_RESULTS_CSV)
        self.matched_txt_name = tk.StringVar(value=DEFAULT_MATCHED_PATHS_TXT)
        self.preview_text = tk.StringVar(value="Preview: scan inputs and add conditions to see matched count")

        self.match_mode.trace_add("write", lambda *_args: self._update_preview_text())

        self.protocol("WM_DELETE_WINDOW", self._on_close)
        self._build_ui()
        self._load_config_if_available()

    def _set_window_icon(self, window: Optional[tk.Toplevel] = None) -> None:
        """Set the Tk window icon when the icon asset is available.

        Passing a specific Toplevel lets child dialogs, such as the About window,
        use the same icon as the main application window.
        """

        target = window if window is not None else self
        icon_path = resource_path("assets/cognex_xml_tool.ico")
        if icon_path.exists():
            try:
                target.iconbitmap(str(icon_path))
            except Exception:
                # Icon loading can fail on some non-Windows systems; the app should still run.
                pass

    # ------------------------------------------------------------------
    # UI layout
    # ------------------------------------------------------------------

    def _build_ui(self) -> None:
        """Build a scrollable main window."""

        container = ttk.Frame(self)
        container.pack(fill="both", expand=True)

        canvas = tk.Canvas(container, highlightthickness=0)
        scrollbar = ttk.Scrollbar(container, orient="vertical", command=canvas.yview)
        self.scroll_frame = ttk.Frame(canvas, padding=12)

        self.scroll_frame.bind("<Configure>", lambda _event: canvas.configure(scrollregion=canvas.bbox("all")))
        canvas_window = canvas.create_window((0, 0), window=self.scroll_frame, anchor="nw")
        canvas.configure(yscrollcommand=scrollbar.set)

        def resize_inner(event: tk.Event) -> None:
            canvas.itemconfigure(canvas_window, width=event.width)

        canvas.bind("<Configure>", resize_inner)
        canvas.pack(side="left", fill="both", expand=True)
        scrollbar.pack(side="right", fill="y")

        def on_mousewheel(event: tk.Event) -> None:
            canvas.yview_scroll(int(-1 * (event.delta / 120)), "units")

        canvas.bind_all("<MouseWheel>", on_mousewheel)

        header = ttk.Frame(self.scroll_frame)
        header.pack(fill="x")
        ttk.Label(header, text=APP_NAME, font=("Segoe UI", 16, "bold")).pack(side="left", anchor="w")
        ttk.Button(header, text="ⓘ", width=3, command=self._show_about).pack(side="right")

        ttk.Label(
            self.scroll_frame,
            text="Load Cognex XML image metadata + Cognex CSV actual results, select result conditions, then create CSV/TXT outputs.",
        ).pack(anchor="w", pady=(2, 10))

        top = ttk.Frame(self.scroll_frame)
        top.pack(fill="both", expand=False)
        top.columnconfigure(0, weight=1)
        top.columnconfigure(1, weight=1)

        self._build_input_frame(top).grid(row=0, column=0, sticky="nsew", padx=(0, 8))
        self._build_settings_frame(top).grid(row=0, column=1, sticky="nsew", padx=(8, 0))

        middle = ttk.Frame(self.scroll_frame)
        middle.pack(fill="both", expand=True, pady=(10, 10))
        middle.columnconfigure(0, weight=1)
        middle.columnconfigure(1, weight=1)

        self._build_detected_tests_frame(middle).grid(row=0, column=0, sticky="nsew", padx=(0, 8))
        self._build_conditions_frame(middle).grid(row=0, column=1, sticky="nsew", padx=(8, 0))

        self._build_action_frame(self.scroll_frame).pack(fill="x", pady=(0, 10))
        self._build_log_frame(self.scroll_frame).pack(fill="both", expand=True)

        self._log("Ready. Add XML file(s), select the Cognex CSV result file, then click Scan XML + CSV.")

    def _build_input_frame(self, parent: ttk.Frame) -> ttk.LabelFrame:
        frame = ttk.LabelFrame(parent, text="1. Inputs", padding=10)
        frame.columnconfigure(0, weight=1)
        frame.rowconfigure(1, weight=1)

        ttk.Label(frame, text="XML file(s) for image names/paths:").grid(row=0, column=0, columnspan=4, sticky="w")
        self.xml_listbox = tk.Listbox(frame, height=5, exportselection=False)
        self.xml_listbox.grid(row=1, column=0, columnspan=4, sticky="nsew", pady=(4, 8))

        ttk.Button(frame, text="Add XML(s)", command=self._add_xml_files).grid(row=2, column=0, sticky="ew", padx=(0, 4))
        ttk.Button(frame, text="Remove selected", command=self._remove_selected_xml).grid(row=2, column=1, sticky="ew", padx=4)
        ttk.Button(frame, text="Clear XMLs", command=self._clear_xml_files).grid(row=2, column=2, sticky="ew", padx=4)

        ttk.Label(frame, text="CSV actual result file:").grid(row=3, column=0, sticky="w", pady=(10, 3))
        self.csv_entry = ttk.Entry(frame)
        self.csv_entry.grid(row=4, column=0, columnspan=3, sticky="ew", pady=(0, 4))
        ttk.Button(frame, text="Browse CSV", command=self._browse_csv_file).grid(row=4, column=3, sticky="ew", padx=(8, 0), pady=(0, 4))

        ttk.Button(frame, text="Scan XML + CSV", command=self._scan_inputs).grid(row=5, column=0, columnspan=4, sticky="ew", pady=(8, 0))
        return frame

    def _build_settings_frame(self, parent: ttk.Frame) -> ttk.LabelFrame:
        frame = ttk.LabelFrame(parent, text="2. Settings", padding=10)
        frame.columnconfigure(1, weight=1)

        ttk.Label(frame, text="Output base folder:").grid(row=0, column=0, sticky="w", padx=(0, 8), pady=3)
        ttk.Entry(frame, textvariable=self.output_folder).grid(row=0, column=1, sticky="ew", pady=3)
        ttk.Button(frame, text="Browse", command=lambda: self._browse_folder(self.output_folder)).grid(row=0, column=2, padx=(8, 0), pady=3)

        ttk.Label(frame, text="Image folder override:").grid(row=1, column=0, sticky="w", padx=(0, 8), pady=3)
        ttk.Entry(frame, textvariable=self.image_root).grid(row=1, column=1, sticky="ew", pady=3)
        ttk.Button(frame, text="Browse", command=lambda: self._browse_folder(self.image_root)).grid(row=1, column=2, padx=(8, 0), pady=3)
        ttk.Label(frame, text="Optional. Leave blank to use image paths from XML.").grid(row=2, column=1, sticky="w", pady=(0, 5))

        ttk.Label(frame, text="Image transfer folder:").grid(row=3, column=0, sticky="w", padx=(0, 8), pady=3)
        ttk.Entry(frame, textvariable=self.copy_folder).grid(row=3, column=1, sticky="ew", pady=3)
        ttk.Button(frame, text="Browse", command=lambda: self._browse_folder(self.copy_folder)).grid(row=3, column=2, padx=(8, 0), pady=3)
        ttk.Label(frame, text="Optional. Leave blank to use an images folder inside each run output folder.").grid(row=4, column=1, sticky="w", pady=(0, 5))

        match_label = ttk.Label(frame, text="Match mode ⓘ:")
        match_label.grid(row=5, column=0, sticky="w", padx=(0, 8), pady=3)
        ToolTip(
            match_label,
            "ALL means every selected condition must match. Example: Inspection A = Pass AND Inspection B = Fail.\n\n"
            "ANY means at least one selected condition must match. Example: Inspection A = Fail OR Inspection B = Fail.",
        )
        ttk.Combobox(
            frame,
            textvariable=self.match_mode,
            values=[MATCH_MODE_ALL, MATCH_MODE_ANY],
            state="readonly",
        ).grid(row=5, column=1, columnspan=2, sticky="ew", pady=3)

        ttk.Label(frame, text="All results CSV:").grid(row=6, column=0, sticky="w", padx=(0, 8), pady=3)
        ttk.Entry(frame, textvariable=self.all_csv_name).grid(row=6, column=1, sticky="ew", pady=3)

        ttk.Label(frame, text="Matched results CSV:").grid(row=7, column=0, sticky="w", padx=(0, 8), pady=3)
        ttk.Entry(frame, textvariable=self.matched_csv_name).grid(row=7, column=1, sticky="ew", pady=3)

        ttk.Label(frame, text="Matched paths TXT:").grid(row=8, column=0, sticky="w", padx=(0, 8), pady=3)
        ttk.Entry(frame, textvariable=self.matched_txt_name).grid(row=8, column=1, sticky="ew", pady=3)

        buttons = ttk.Frame(frame)
        buttons.grid(row=9, column=0, columnspan=3, sticky="ew", pady=(8, 0))
        buttons.columnconfigure(0, weight=1)
        buttons.columnconfigure(1, weight=1)
        ttk.Button(buttons, text="Save config", command=self._save_config).grid(row=0, column=0, sticky="ew", padx=(0, 4))
        ttk.Button(buttons, text="Load config", command=self._load_config_manual).grid(row=0, column=1, sticky="ew", padx=(4, 0))
        return frame

    def _build_detected_tests_frame(self, parent: ttk.Frame) -> ttk.LabelFrame:
        frame = ttk.LabelFrame(parent, text="3. Detected CSV result columns", padding=10)
        frame.columnconfigure(0, weight=1)
        frame.rowconfigure(0, weight=1)

        columns = ("csv_column", "rows", "values")
        self.tests_tree = ttk.Treeview(frame, columns=columns, show="tree headings", selectmode="browse", height=8)
        self.tests_tree.heading("#0", text="Test name")
        self.tests_tree.heading("csv_column", text="CSV column")
        self.tests_tree.heading("rows", text="Rows")
        self.tests_tree.heading("values", text="Detected results")
        self.tests_tree.column("#0", width=170, stretch=True)
        self.tests_tree.column("csv_column", width=140, stretch=True)
        self.tests_tree.column("rows", width=60, anchor="e", stretch=False)
        self.tests_tree.column("values", width=150, stretch=True)
        self.tests_tree.grid(row=0, column=0, columnspan=3, sticky="nsew")
        self.tests_tree.bind("<<TreeviewSelect>>", lambda _event: self._update_result_choices())
        self.tests_tree.bind("<Double-1>", lambda _event: self._add_condition())

        scroll = ttk.Scrollbar(frame, orient="vertical", command=self.tests_tree.yview)
        self.tests_tree.configure(yscrollcommand=scroll.set)
        scroll.grid(row=0, column=3, sticky="ns")

        ttk.Label(frame, text="Result of interest:").grid(row=1, column=0, sticky="w", pady=(8, 0))
        self.result_combo = ttk.Combobox(frame, textvariable=self.target_result, values=["Pass", "Fail", ANY_TARGET, MISSING_TARGET], width=24)
        self.result_combo.grid(row=1, column=1, sticky="w", pady=(8, 0))
        ttk.Button(frame, text="Add to output/filter", command=self._add_condition).grid(row=1, column=2, sticky="e", pady=(8, 0))

        ttk.Label(frame, text="Use '(Any / output only)' to include a CSV result column without filtering on it.").grid(row=2, column=0, columnspan=3, sticky="w", pady=(5, 0))
        return frame

    def _build_conditions_frame(self, parent: ttk.Frame) -> ttk.LabelFrame:
        frame = ttk.LabelFrame(parent, text="4. Selected output/filter conditions", padding=10)
        frame.columnconfigure(0, weight=1)
        frame.rowconfigure(0, weight=1)

        columns = ("order", "test", "target")
        self.conditions_tree = ttk.Treeview(frame, columns=columns, show="headings", selectmode="browse", height=8)
        self.conditions_tree.heading("order", text="Order")
        self.conditions_tree.heading("test", text="Test name")
        self.conditions_tree.heading("target", text="Result of interest")
        self.conditions_tree.column("order", width=55, anchor="center", stretch=False)
        self.conditions_tree.column("test", width=250, stretch=True)
        self.conditions_tree.column("target", width=160, stretch=True)
        self.conditions_tree.grid(row=0, column=0, columnspan=4, sticky="nsew")

        scroll = ttk.Scrollbar(frame, orient="vertical", command=self.conditions_tree.yview)
        self.conditions_tree.configure(yscrollcommand=scroll.set)
        scroll.grid(row=0, column=4, sticky="ns")

        button_row = ttk.Frame(frame)
        button_row.grid(row=1, column=0, columnspan=4, sticky="ew", pady=(8, 0))
        for i in range(4):
            button_row.columnconfigure(i, weight=1, uniform="condition_buttons")
        ttk.Button(button_row, text="Move up", command=lambda: self._move_condition(-1)).grid(row=0, column=0, sticky="ew", padx=(0, 3))
        ttk.Button(button_row, text="Move down", command=lambda: self._move_condition(1)).grid(row=0, column=1, sticky="ew", padx=3)
        ttk.Button(button_row, text="Remove", command=self._remove_condition).grid(row=0, column=2, sticky="ew", padx=3)
        ttk.Button(button_row, text="Clear", command=self._clear_conditions).grid(row=0, column=3, sticky="ew", padx=(3, 0))

        ttk.Label(frame, text="Order controls CSV column order. Filters control which rows appear in matched outputs.").grid(row=2, column=0, columnspan=4, sticky="w", pady=(6, 0))
        return frame

    def _build_action_frame(self, parent: ttk.Frame) -> ttk.LabelFrame:
        frame = ttk.LabelFrame(parent, text="5. Preview, run, and transfer images", padding=10)
        for column in range(4):
            frame.columnconfigure(column, weight=1, uniform="action_buttons")

        style = ttk.Style()
        style.configure("Run.TButton", foreground="dark green")
        ttk.Button(frame, text="Preview matched count", command=self._preview_matches).grid(row=0, column=0, sticky="ew", padx=(0, 4))
        ttk.Button(frame, text="▶ Run: create outputs", command=self._process, style="Run.TButton").grid(row=0, column=1, sticky="ew", padx=4)
        ttk.Button(frame, text="Copy matched images", command=self._copy_matched_images).grid(row=0, column=2, sticky="ew", padx=4)
        ttk.Button(frame, text="Move matched images", command=self._move_matched_images).grid(row=0, column=3, sticky="ew", padx=(4, 0))
        ttk.Label(frame, textvariable=self.preview_text).grid(row=1, column=0, columnspan=4, sticky="w", pady=(8, 0))
        return frame

    def _build_log_frame(self, parent: ttk.Frame) -> ttk.LabelFrame:
        frame = ttk.LabelFrame(parent, text="Log", padding=10)
        frame.columnconfigure(0, weight=1)
        frame.rowconfigure(0, weight=1)
        self.log_text = ScrolledText(frame, height=8, wrap="word")
        self.log_text.grid(row=0, column=0, sticky="nsew")
        return frame

    # ------------------------------------------------------------------
    # File selection and scan actions
    # ------------------------------------------------------------------

    def _add_xml_files(self) -> None:
        files = filedialog.askopenfilenames(title="Select Cognex XML file(s)", filetypes=[("XML files", "*.xml"), ("All files", "*.*")])
        for file in files:
            path = Path(file)
            if path not in self.xml_files:
                self.xml_files.append(path)
                self.xml_listbox.insert("end", str(path))
        self._autosave_config_quietly()

    def _remove_selected_xml(self) -> None:
        selected = list(self.xml_listbox.curselection())
        for index in reversed(selected):
            del self.xml_files[index]
            self.xml_listbox.delete(index)
        self._autosave_config_quietly()

    def _clear_xml_files(self) -> None:
        self.xml_files.clear()
        self.xml_listbox.delete(0, "end")
        self.merged = None
        self._clear_tests_tree()
        self._autosave_config_quietly()

    def _browse_csv_file(self) -> None:
        file = filedialog.askopenfilename(title="Select Cognex CSV result file", filetypes=[("CSV files", "*.csv"), ("All files", "*.*")])
        if file:
            self.csv_file = Path(file)
            self.csv_entry.delete(0, "end")
            self.csv_entry.insert(0, str(self.csv_file))
            self.output_folder.set(str(self.csv_file.resolve().parent))
            self.copy_folder.set("")
            self._autosave_config_quietly()

    def _scan_inputs(self) -> None:
        try:
            if not self.xml_files:
                messagebox.showwarning("No XML file", "Please add at least one Cognex XML file first.")
                return

            csv_text = self.csv_entry.get().strip()
            if csv_text:
                self.csv_file = Path(csv_text)
            if self.csv_file is None:
                messagebox.showwarning("No CSV file", "Please select the Cognex CSV actual result file.")
                return

            missing_xml = [str(path) for path in self.xml_files if not path.exists()]
            if missing_xml:
                raise FileNotFoundError("Could not find XML file(s):\n" + "\n".join(missing_xml))
            if not self.csv_file.exists():
                raise FileNotFoundError(f"Could not find CSV file: {self.csv_file}")

            if not self.output_folder.get().strip():
                self.output_folder.set(str(self.csv_file.resolve().parent))
            if not self.copy_folder.get().strip():
                self.copy_folder.set("")

            self._clear_tests_tree()
            self.last_summary = None
            self._log("Scanning XML image metadata and CSV actual results...")
            self.merged = merge_xml_and_csv(self.xml_files, self.csv_file)
            self._populate_tests_tree()

            self._log(f"XML images loaded: {self.merged.xml_images_loaded}")
            self._log(f"CSV rows loaded: {self.merged.csv_rows_loaded}")
            self._log(f"CSV matching mode: {self.merged.csv_key_mode}")
            self._log(f"Images with matching CSV data: {self.merged.csv_groups_matched}")
            if self.merged.csv_groups_unmatched:
                self._log(f"Unmatched/extra CSV groups or rows: {self.merged.csv_groups_unmatched}")
            self._log(f"Detected CSV result columns: {len(self.merged.tests)}")
            if not self.merged.tests:
                self._log("Warning: no result columns detected. Columns ending in 'Pass' or boolean result columns are expected.")
            self._log("Select detected result columns, choose result of interest, then run outputs.")
            self._update_preview_text()
            self._autosave_config_quietly()
        except Exception as exc:
            self._handle_error(exc)

    def _clear_tests_tree(self) -> None:
        for item in self.tests_tree.get_children():
            self.tests_tree.delete(item)

    def _populate_tests_tree(self) -> None:
        self._clear_tests_tree()
        if self.merged is None:
            return

        test_names = sorted(self.merged.tests, key=lambda name: (-self.merged.tests[name].rows_with_data, name.lower()))
        for test_name in test_names:
            test = self.merged.tests[test_name]
            values = sorted(test.detected_values, key=str.lower)
            self.tests_tree.insert("", "end", iid=test_name, text=test_name, values=(test.csv_column, test.rows_with_data, ", ".join(values)))

        if test_names:
            self.tests_tree.selection_set(test_names[0])
            self.tests_tree.focus(test_names[0])
            self._update_result_choices()

    # ------------------------------------------------------------------
    # Condition selection actions
    # ------------------------------------------------------------------

    def _selected_test_name(self) -> Optional[str]:
        selected = self.tests_tree.selection()
        return str(selected[0]) if selected else None

    def _update_result_choices(self) -> None:
        selected_test = self._selected_test_name()
        values: List[str] = []
        if self.merged and selected_test and selected_test in self.merged.tests:
            values = sorted(self.merged.tests[selected_test].detected_values, key=str.lower)

        combo_values = values + [ANY_TARGET, MISSING_TARGET]
        self.result_combo.configure(values=combo_values)
        if "Fail" in values:
            self.target_result.set("Fail")
        elif "Pass" in values:
            self.target_result.set("Pass")
        elif values:
            self.target_result.set(values[0])
        else:
            self.target_result.set(ANY_TARGET)

    def _add_condition(self) -> None:
        test_name = self._selected_test_name()
        if not test_name:
            messagebox.showwarning("No test selected", "Please select a detected CSV result column first.")
            return
        target = self.target_result.get().strip() or ANY_TARGET
        self.conditions.append(Condition(test_name=test_name, target_result=target))
        self._refresh_conditions_tree()
        self._autosave_config_quietly()

    def _refresh_conditions_tree(self) -> None:
        for item in self.conditions_tree.get_children():
            self.conditions_tree.delete(item)
        for index, condition in enumerate(self.conditions, start=1):
            self.conditions_tree.insert("", "end", iid=str(index - 1), values=(index, condition.test_name, condition.target_result))
        self._update_preview_text()

    def _selected_condition_index(self) -> Optional[int]:
        selected = self.conditions_tree.selection()
        return int(selected[0]) if selected else None

    def _move_condition(self, direction: int) -> None:
        index = self._selected_condition_index()
        if index is None:
            return
        new_index = index + direction
        if new_index < 0 or new_index >= len(self.conditions):
            return
        self.conditions[index], self.conditions[new_index] = self.conditions[new_index], self.conditions[index]
        self._refresh_conditions_tree()
        self.conditions_tree.selection_set(str(new_index))
        self.conditions_tree.focus(str(new_index))
        self._autosave_config_quietly()

    def _remove_condition(self) -> None:
        index = self._selected_condition_index()
        if index is None:
            return
        del self.conditions[index]
        self._refresh_conditions_tree()
        self._autosave_config_quietly()

    def _clear_conditions(self) -> None:
        self.conditions.clear()
        self._refresh_conditions_tree()
        self._autosave_config_quietly()

    # ------------------------------------------------------------------
    # Processing and copy actions
    # ------------------------------------------------------------------

    def _browse_folder(self, variable: tk.StringVar) -> None:
        folder = filedialog.askdirectory(title="Select folder")
        if folder:
            variable.set(folder)
            self._autosave_config_quietly()

    def _get_output_base_folder(self) -> Path:
        """Return the base output folder, defaulting to the CSV parent folder."""

        base_text = self.output_folder.get().strip()
        if base_text:
            base = Path(base_text)
        else:
            base = default_output_base_folder(self.csv_file)
            self.output_folder.set(str(base))
        base.mkdir(parents=True, exist_ok=True)
        return base

    def _get_run_output_folder(self) -> Path:
        """Return the result-specific output folder for the current selected conditions."""

        base = self._get_output_base_folder()
        folder_name = condition_folder_name(self.conditions, self.match_mode.get())
        folder = base / folder_name
        folder.mkdir(parents=True, exist_ok=True)
        return folder

    def _get_image_transfer_folder(self) -> Path:
        """Return custom image transfer folder or the default images subfolder for the last run."""

        custom = self.copy_folder.get().strip()
        if custom:
            folder = Path(custom)
        elif self.last_summary and self.last_summary.output_folder:
            folder = self.last_summary.output_folder / DEFAULT_IMAGE_FOLDER
        else:
            folder = self._get_run_output_folder() / DEFAULT_IMAGE_FOLDER
        folder.mkdir(parents=True, exist_ok=True)
        return folder

    def _update_preview_text(self) -> None:
        """Update the small preview label without showing pop-ups."""

        if self.merged is None:
            self.preview_text.set("Preview: scan inputs and add conditions to see matched count")
            return
        if not self.conditions:
            self.preview_text.set(f"Preview: {len(ordered_records(self.merged))} images loaded, no filters selected")
            return
        matched = count_matching_records(self.merged, self.conditions, self.match_mode.get())
        active_filters = sum(1 for condition in self.conditions if condition_is_filter(condition))
        self.preview_text.set(f"Preview: {matched} matching images from {len(ordered_records(self.merged))} total images ({active_filters} active filter conditions)")

    def _preview_matches(self) -> None:
        """Show the current matched count before the user creates outputs or copies images."""

        if self.merged is None:
            messagebox.showwarning("Scan first", "Please scan the XML + CSV inputs first.")
            return
        if not self.conditions:
            messagebox.showwarning("No selected tests", "Please add at least one CSV result column to the selected conditions list.")
            return
        self._update_preview_text()
        self._log(self.preview_text.get())
        messagebox.showinfo("Preview matched count", self.preview_text.get())

    def _process(self) -> None:
        try:
            if self.merged is None:
                messagebox.showwarning("Scan first", "Please scan the XML + CSV inputs first.")
                return
            if not self.conditions:
                messagebox.showwarning("No selected tests", "Please add at least one CSV result column to the selected conditions list.")
                return

            output_folder = self._get_run_output_folder()
            image_root = self.image_root.get().strip() or None
            summary = process_outputs(
                merged=self.merged,
                conditions=self.conditions,
                output_folder=output_folder,
                image_root_override=image_root,
                match_mode=self.match_mode.get(),
                all_csv_name=self.all_csv_name.get().strip() or DEFAULT_ALL_RESULTS_CSV,
                matched_csv_name=self.matched_csv_name.get().strip() or DEFAULT_MATCHED_RESULTS_CSV,
                matched_txt_name=self.matched_txt_name.get().strip() or DEFAULT_MATCHED_PATHS_TXT,
            )
            self.last_summary = summary
            self._update_preview_text()
            self._autosave_config_quietly()
            self._show_summary(summary)
        except Exception as exc:
            self._handle_error(exc)

    def _resolve_current_matched_txt_path(self) -> Path:
        if self.last_summary and self.last_summary.matched_paths_txt:
            return self.last_summary.matched_paths_txt
        return self._get_run_output_folder() / (self.matched_txt_name.get().strip() or DEFAULT_MATCHED_PATHS_TXT)

    def _copy_matched_images(self) -> None:
        try:
            paths_txt = self._resolve_current_matched_txt_path()
            destination = self._get_image_transfer_folder()
            summary = copy_images_from_txt(paths_txt, destination)
            self._log(f"Copy complete. Copied: {summary.copied}, missing: {summary.missing}, errors: {summary.errors}")
            messagebox.showinfo(
                "Copy complete",
                f"Copied: {summary.copied}\nMissing: {summary.missing}\nErrors: {summary.errors}\nDestination:\n{summary.destination_folder}",
            )
        except Exception as exc:
            self._handle_error(exc)

    def _move_matched_images(self) -> None:
        try:
            paths_txt = self._resolve_current_matched_txt_path()
            destination = self._get_image_transfer_folder()
            if not messagebox.askyesno(
                "Move matched images",
                "This will move the matched image files out of their current folder. Continue?",
            ):
                return
            summary = move_images_from_txt(paths_txt, destination)
            self._log(f"Move complete. Moved: {summary.copied}, missing: {summary.missing}, errors: {summary.errors}")
            messagebox.showinfo(
                "Move complete",
                f"Moved: {summary.copied}\nMissing: {summary.missing}\nErrors: {summary.errors}\nDestination:\n{summary.destination_folder}",
            )
        except Exception as exc:
            self._handle_error(exc)

    def _show_summary(self, summary: OutputSummary) -> None:
        self._log("Output complete.")
        self._log(f"Total images: {summary.total_images}")
        self._log(f"Selected tests: {summary.tests_selected}")
        self._log(f"Active filter conditions: {summary.filter_conditions}")
        self._log(f"Matched images: {summary.matched_images}")
        self._log(f"Output folder: {summary.output_folder}")
        self._log(f"All results CSV: {summary.all_results_csv}")
        self._log(f"Matched results CSV: {summary.matched_results_csv}")
        self._log(f"Matched paths TXT: {summary.matched_paths_txt}")
        messagebox.showinfo(
            "Outputs created",
            f"Total images: {summary.total_images}\n"
            f"Matched images: {summary.matched_images}\n\n"
            f"Output folder:\n{summary.output_folder}\n\n"
            f"All results CSV:\n{summary.all_results_csv}\n\n"
            f"Matched paths TXT:\n{summary.matched_paths_txt}",
        )

    # ------------------------------------------------------------------
    # Config actions
    # ------------------------------------------------------------------

    def _config_dict(self) -> Dict[str, object]:
        return {
            "app_version": APP_VERSION,
            "xml_files": [str(path) for path in self.xml_files],
            "csv_file": str(self.csv_file or self.csv_entry.get().strip() or ""),
            "output_folder": self.output_folder.get(),
            "image_root": self.image_root.get(),
            "copy_folder": self.copy_folder.get(),
            "match_mode": self.match_mode.get(),
            "all_csv_name": self.all_csv_name.get(),
            "matched_csv_name": self.matched_csv_name.get(),
            "matched_txt_name": self.matched_txt_name.get(),
            "conditions": [{"test_name": c.test_name, "target_result": c.target_result} for c in self.conditions],
        }

    def _apply_config(self, data: Dict[str, object]) -> None:
        self.xml_files = [Path(text) for text in data.get("xml_files", []) if str(text).strip()]
        self.xml_listbox.delete(0, "end")
        for path in self.xml_files:
            self.xml_listbox.insert("end", str(path))

        csv_text = str(data.get("csv_file", "") or "")
        self.csv_file = Path(csv_text) if csv_text else None
        self.csv_entry.delete(0, "end")
        self.csv_entry.insert(0, csv_text)

        self.output_folder.set(str(data.get("output_folder", self.output_folder.get()) or self.output_folder.get()))
        self.image_root.set(str(data.get("image_root", "") or ""))
        self.copy_folder.set(str(data.get("copy_folder", self.copy_folder.get()) or self.copy_folder.get()))
        self.match_mode.set(str(data.get("match_mode", MATCH_MODE_ALL) or MATCH_MODE_ALL))
        self.all_csv_name.set(str(data.get("all_csv_name", DEFAULT_ALL_RESULTS_CSV) or DEFAULT_ALL_RESULTS_CSV))
        self.matched_csv_name.set(str(data.get("matched_csv_name", DEFAULT_MATCHED_RESULTS_CSV) or DEFAULT_MATCHED_RESULTS_CSV))
        self.matched_txt_name.set(str(data.get("matched_txt_name", DEFAULT_MATCHED_PATHS_TXT) or DEFAULT_MATCHED_PATHS_TXT))

        self.conditions = []
        for item in data.get("conditions", []):
            if isinstance(item, dict) and item.get("test_name"):
                self.conditions.append(Condition(test_name=str(item.get("test_name")), target_result=str(item.get("target_result", ANY_TARGET))))
        self._refresh_conditions_tree()

    def _save_config(self) -> None:
        try:
            ensure_config_folder()
            path = config_path()
            path.write_text(json.dumps(self._config_dict(), indent=2), encoding="utf-8")
            self._log(f"Saved config: {path}")
            messagebox.showinfo("Config saved", f"Saved config:\n{path}")
        except Exception as exc:
            self._handle_error(exc)

    def _autosave_config_quietly(self) -> None:
        try:
            ensure_config_folder()
            config_path().write_text(json.dumps(self._config_dict(), indent=2), encoding="utf-8")
        except Exception:
            pass

    def _load_config_if_available(self) -> None:
        """Auto-load the saved config from the stable AppData location.

        If a user previously ran an older portable build, we also look for the
        old beside-the-EXE config once and migrate it into AppData.
        """

        path = config_path()
        legacy_path = legacy_config_path()

        if not path.exists() and legacy_path.exists() and legacy_path != path:
            try:
                ensure_config_folder()
                path.write_text(legacy_path.read_text(encoding="utf-8"), encoding="utf-8")
                self._log(f"Migrated config to: {path}")
            except Exception as exc:
                self._log(f"Could not migrate old config: {exc}")

        if not path.exists():
            self._log("No saved config found; using defaults.")
            self._log(f"Default config location: {path}")
            return
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            self._apply_config(data)
            self._log(f"Loaded config: {path}")
        except Exception as exc:
            self._log(f"Could not load config: {exc}")

    def _load_config_manual(self) -> None:
        file = filedialog.askopenfilename(title="Load config", filetypes=[("JSON files", "*.json"), ("All files", "*.*")])
        if not file:
            return
        try:
            data = json.loads(Path(file).read_text(encoding="utf-8"))
            self._apply_config(data)
            self._log(f"Loaded config: {file}")
        except Exception as exc:
            self._handle_error(exc)

    def _on_close(self) -> None:
        self._autosave_config_quietly()
        self.destroy()

    # ------------------------------------------------------------------
    # Misc UI helpers
    # ------------------------------------------------------------------

    def _show_about(self) -> None:
        window = tk.Toplevel(self)
        window.title(f"About {APP_NAME}")
        window.resizable(False, False)
        window.transient(self)
        self._set_window_icon(window)

        frame = ttk.Frame(window, padding=16)
        frame.pack(fill="both", expand=True)

        header = ttk.Frame(frame)
        header.pack(fill="x")

        icon_image = None
        png_path = resource_path("assets/cognex_xml_tool.png")
        if png_path.exists():
            try:
                icon_image = tk.PhotoImage(file=str(png_path)).subsample(2, 2)
                icon_label = ttk.Label(header, image=icon_image)
                icon_label.image = icon_image  # Keep a reference so Tk does not garbage-collect it.
                icon_label.pack(side="left", padx=(0, 12))
            except Exception:
                icon_image = None

        title_frame = ttk.Frame(header)
        title_frame.pack(side="left", fill="x", expand=True)
        ttk.Label(title_frame, text=APP_NAME, font=("Segoe UI", 14, "bold")).pack(anchor="w")
        ttk.Label(title_frame, text=f"Version: {APP_VERSION}").pack(anchor="w", pady=(4, 0))

        ttk.Label(frame, text=f"Author: {APP_AUTHOR}").pack(anchor="w", pady=(10, 0))
        ttk.Label(frame, text=f"License: {APP_LICENSE}").pack(anchor="w", pady=(6, 0))
        ttk.Label(frame, text=f"Config: {config_path()}", wraplength=460).pack(anchor="w", pady=(8, 0))
        link = ttk.Label(frame, text=APP_GITHUB, foreground="blue", cursor="hand2")
        link.pack(anchor="w", pady=(8, 0))
        link.bind("<Button-1>", lambda _event: webbrowser.open(APP_GITHUB))
        ttk.Button(frame, text="Close", command=window.destroy).pack(anchor="e", pady=(14, 0))

    def _log(self, message: str) -> None:
        self.log_text.insert("end", message + "\n")
        self.log_text.see("end")

    def _handle_error(self, exc: Exception) -> None:
        error_text = "".join(traceback.format_exception_only(type(exc), exc)).strip()
        self._log("ERROR: " + error_text)
        messagebox.showerror("Error", error_text)


# -----------------------------------------------------------------------------
# Entry point
# -----------------------------------------------------------------------------

def main() -> None:
    set_windows_app_user_model_id()
    app = CognexXmlToolGui()
    app.mainloop()


if __name__ == "__main__":
    main()
